clear;
clc;
cd ~/Documents/MATH149/matlab_examples;
load_javaplex;
cd ~/Documents/MATH149/git;
%pc = get_pointcloud('test.jpg');
pc = get_pointcloud('Letters/B/1.jpg');
xmid = int32((max(pc(:,1)) + min(pc(:, 1))) / 2);
ymid = int32((max(pc(:,2)) + min(pc(:, 2))) / 2);
pc_left = pc;
pc_up = sortrows(pc);
pc_up = [pc_up(:,2), pc_up(:,1)];
map_left = get_vertex_points_map(pc_left);
map_up = get_vertex_points_map(pc_up);
stream_left = connect_vertices(map_left);
stream_up = connect_vertices(map_up);
persistence = api.Plex4.getModularSimplicialAlgorithm(2,2);
intervals_left = persistence.computeAnnotatedIndexIntervals(stream_left);
intervals_up = persistence.computeAnnotatedIndexIntervals(stream_up);
%plot_barcodes(intervals);